[project]
name = "president-dates-game"
version = "0.0.0"
description = "Game to match the year to the president term"
authors = []
requires-python = ">=3.12,<4"
readme = "README.md"
dependencies = [
    "pydantic>=2.6.4,<3",
    "textual>=6.7.1,<7",
]

[tool.uv]
package = false
