[tool.poetry]
name = "president-dates-game"
version = "0.0.0"
description = "Game to match the year to the president term"
authors = []
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.6.4"
textual = "^6.7.1"
